### ISSUE TITLE
Add AppImage deployment to Travis CI

### ISSUE THREAD

**Issue by Symbian9** [kefir500/apk-editor-studio#4]
Compile *APK Editor Studio* on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) for Linux to your GitHub Releases page.

<details>

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

### TODO

1. https://github.com/appimage/appimagekit
1.1 https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/probonopd/uploadtool

**PLEASE NOTE:** For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) **prior to merging this**, if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

</details>

For example, take a look on on [Android File Transfer for Linux](http://whoozle.github.io/android-file-transfer-linux/) repo on GitHub:

- https://github.com/whoozle/android-file-transfer-linux
  - https://github.com/whoozle/android-file-transfer-linux/blob/master/.travis.yml
  - https://github.com/whoozle/android-file-transfer-linux/releases/tag/continuous

If you have questions, AppImage developers (i.e. @probonopd and other) are on `#AppImage` on irc.freenode.net

**Comment by probonopd** [comment]
Can you send a PR @Symbian9?

**Comment by Symbian9** [comment]
> Can you send a PR `@Symbian9`?

Next month.

**Comment by kefir500** [comment]
Started to work on this in the [`appimage`](https://github.com/kefir500/apk-editor-studio/tree/appimage) branch.

### Checklist

- [x] Add AppImage build script.
  - [ ] Fix `qt.network.ssl: Incompatible version of OpenSSL` on some distributions.
- [x] Add AppImage deployment via Travis CI.
  - [ ] Fix non-native GUI style &#42;.
- [ ] Fix internal paths to correspond portability.
- [ ] Test AppImage package.

&#42; *The possible solution is to use the `beineri` PPA, however currently it conflicts with the CI DEB build.*

**Comment by Ibuprophen** [comment]
How's the progress going with your checklist @kefir500? 


~Ibuprophen

**Comment by kefir500** [comment]
@Ibuprophen Nearly everything seems to be ready. I just have to do some testing on different Linux distributions. The `AppImage` neutral build for testing can be [downloaded here](https://github.com/kefir500/apk-editor-studio/releases/download/development/apk-editor-studio_linux_dev.AppImage).

Still trying to figure out the `OpenSSL` issue, though. Actually, this is not a critical dependency, however without it APK Editor Studio won't be able to check for updates.

It seems to **work fine** with the Debian-based distributions:

- Ubuntu 16.04
- Ubuntu 18.04
- Linux Mint 19.2

However, the **`qt.network.ssl: Incompatible version of OpenSSL`** error appears on the following distributions:

- openSUSE 15.1
- Fedora 30
- Manjaro 18.1.0

Probably, @probonopd could shed some light on it.

**Comment by Ibuprophen** [comment]
I agree with you regarding @probonopd shedding some light as I don't currently operate any of those distributions. 

I've got 2 PC Towers and 3 PC Laptop's which different Windows OS builds installed (actually in the process of getting one of the Laptops setup for Windows 10 Pro). 

One of the towers is my primary PC (that goes without saying) and the rest are used primarily for testing, troubleshooting, etc... the Open Shell Software that I'm currently in a team of four developers. 

I do have some Unix & Linux OS Software that I don't use much at all but, I have used them before under one of the PC's as a dual boot. 

How busy I am... LOL! :-) 


~Ibuprophen
